### ISSUE TITLE
Implot crashes when compiled with address sanitizer on gcc

### ISSUE THREAD

**Issue by qeedquan** [epezent/implot#66]
I used the examples_sdl_opengl3 bundled with imgui and added in the implot code with
ImPlot::ShowDemoWindow() to draw the example code. This triggers a crash when compiled with -fsanitize=address on Linux and GCC 9.3.0 using implot git version
37ee2d4c5402b0e3a5819d07f61815d5fae3bed9

```
=================================================================
==48757==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55bf12668948 at pc 0x55bf1250ef5a bp 0x7ffeebd56060 sp 0x7ffeebd56050
READ of size 4 at 0x55bf12668948 thread T0
    #0 0x55bf1250ef59 in OffsetCalculator ../../implot.cpp:164
    #1 0x55bf1250d61e in ImPlot::SetColormap(int, int) ../../implot.cpp:3499
    #2 0x55bf12510d14 in ImPlot::ImPlotContext::ImPlotContext() ../../implot.cpp:424
    #3 0x55bf1250f062 in __static_initialization_and_destruction_0 ../../implot.cpp:524
    #4 0x55bf1250f09b in _GLOBAL__sub_I__ZN11ImPlotStyleC2Ev ../../implot.cpp:3631
    #5 0x55bf125be26c in __libc_csu_init (/home/qeed/imgui/examples/example_sdl_opengl3/example_sdl_opengl3+0x2a926c)
    #6 0x7fe54894303f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2703f)
    #7 0x55bf123620cd in _start (/home/qeed/imgui/examples/example_sdl_opengl3/example_sdl_opengl3+0x4d0cd)

0x55bf12668948 is located 0 bytes to the right of global variable 'csizes' defined in '../../implot.cpp:3498:16' (0x55bf12668920) of size 40
SUMMARY: AddressSanitizer: global-buffer-overflow ../../implot.cpp:164 in OffsetCalculator
Shadow bytes around the buggy address:
  0x0ab8624c50d0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c50e0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c50f0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c5100: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c5110: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
=>0x0ab8624c5120: f9 f9 f9 f9 00 00 00 00 00[f9]f9 f9 f9 f9 f9 f9
  0x0ab8624c5130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab8624c5140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab8624c5150: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c5160: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0ab8624c5170: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==48757==ABORTING
```
Looking at the location of the crash, the error seems to occur at line 3499
```
  static int csizes[ImPlotColormap_COUNT] = {10,9,9,12,11,11,11,11,11,11};
  static OffsetCalculator<ImPlotCol_COUNT> coffs(csizes);
```
ImPlotCol_COUNT is larger than ImPlotColormap_COUNT and thus it will overwrite memory.
The fix seems to be using ImPlotColormap_COUNT for OffsetCalculator.

**Comment by epezent** [comment]
You are exactly right. It's a mistake. It's been fixed and thank you for bringing this to my attention. Cheers!
